services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-this-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DATABASE_URL=sqlite:///./theai.db
      - UPLOAD_DIR=uploads
      - ASEXUAL_MODEL_PATH=./yolov9cbestsofar 130epocs no finetune.pt
      - RBC_MODEL_PATH=./rbc counter.pt
      - STAGE_MODEL_PATH=./yolov9 for segmenting parasit stages.pt
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-this-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=43200
      - DATABASE_URL=sqlite:///./theai.db
      - UPLOAD_DIR=uploads
      - ASEXUAL_MODEL_PATH=./yolov9cbestsofar 130epocs no finetune.pt
      - RBC_MODEL_PATH=./rbc counter.pt
      - STAGE_MODEL_PATH=./yolov9 for segmenting parasit stages.pt
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
    depends_on:
      - redis
    # Let Celery auto-detect worker count based on system resources
    command: celery -A celery_app worker --loglevel=info
    # Adjusted memory limits based on worker count
    deploy:
      resources:
        limits:
          memory: 6G  # Increased for multiple workers
        reservations:
          memory: 2G
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "celery -A celery_app inspect ping || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  redis_data:
  uploads_data: